name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify the Ruby version you are using
          
      - name: Install dependencies
        run: |
          gem install bundler -v 2.6.2
          bundle install

      - name: Run tests
        run: bundle ruby -I test test/app_test.rb