name: Run Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify the Ruby version you are using

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec ruby -I test test/app_test.rb